<query>

CREATE TABLE [dbo].[{NombreTabla}](
	Cod_Cliente [numeric](12, 0) NOT NULL,
	Nombre_Cliente [nvarchar](200) NOT NULL,
	Num_Identificacion [nvarchar](50) NOT NULL,
	Tipo_persona [nvarchar](25) NOT NULL,
	No_Creditos [int] NOT NULL,
	Deuda_total [numeric](38, 2) NOT NULL,
	Cod_Credito [numeric](15, 0) NOT NULL,
	Tipo_Credito [nvarchar](50) NOT NULL,
	Tipo_Producto [nvarchar](200) NOT NULL,
	Sector [nvarchar](50) NOT NULL,
	Fuente_Fin [nvarchar](50) NOT NULL,
	Codigo_MUC [numeric](15, 0) NOT NULL,
	Monto_Original [numeric](15, 2) NOT NULL,
	Moneda [nvarchar](15) NOT NULL,
	Saldo_principal [numeric](15, 2) NOT NULL,
	Saldo_interes [numeric](15, 2) NOT NULL,
	Monto_Ult_Pago_Ppal [numeric](15, 2) NOT NULL,
	Monto_Ult_Pago_Int [numeric](38, 2) NOT NULL,
	Fecha_Aprobacion [nvarchar](10) NOT NULL,
	Fecha_Desembolso [nvarchar](10) NOT NULL,
	Fecha_Vencimiento [nvarchar](10) NOT NULL,
	Plazo [int] NOT NULL,
	Fecha_primer_pago [nvarchar](10) NOT NULL,
	Fecha_ultimo_pago_ppal [nvarchar](10) NOT NULL,
	Fecha_ultimo_pago_int [nvarchar](10) NOT NULL,
	Fecha_ingreso_mora_ppal [nvarchar](10) NOT NULL,
	Fecha_ingreso_mora_int [nvarchar](10) NOT NULL,
	Frecuencia_pago_ppal [nvarchar](250) NOT NULL,
	Frecuencia_pago_int [nvarchar](250) NOT NULL,
	Cuotas_programadas [numeric](5, 0) NOT NULL,
	Cuotas_pagadas [numeric](5, 0) NOT NULL,
	Cuotas_vencidas [numeric](5, 0) NOT NULL,
	Modalidad [nvarchar](50) NOT NULL,
	Dias_gracia [int] NOT NULL,
	Tipo_tasa [nvarchar](25) NOT NULL,
	Tasa_contractual [numeric](15, 2) NOT NULL,
	Tasa_vigente [numeric](15, 2) NOT NULL,
	Tasa_efectiva_vigente [numeric](15, 2) NOT NULL,
	Tasa_mora [numeric](15, 2) NOT NULL,
	Tipo_garantia [nvarchar](max) NOT NULL,
	Descripcion_garantia [nvarchar](max) NOT NULL,
	Valor_garantia [numeric](38, 2) NOT NULL,
	Monto_cuota [numeric](16, 2) NOT NULL,
	Cuota_total [numeric](38, 2) NOT NULL,
	Principal_corriente [numeric](24, 2) NOT NULL,
	Principal_vencido [numeric](38, 2) NOT NULL,
	Interes_Cte_Vgte [numeric](24, 2) NOT NULL,
	Interes_Cte_Vcdo [numeric](26, 2) NOT NULL,
	Interes_moratorio [numeric](15, 2) NOT NULL,
	Fecha_prox_pago_ppal [nvarchar](10) NOT NULL,
	Fecha_prox_pago_int [nvarchar](10) NOT NULL,
	Dias_mora_principal [int] NOT NULL,
	Dias_mora_intereses [int] NOT NULL,
	Clasificacion [int] NOT NULL,
	Clasificacion_Cliente [int] NOT NULL,
	Provision [numeric](15, 2) NOT NULL,
	Sucursal [nvarchar](100) NOT NULL,
	Asesor_Credito [nvarchar](250) NOT NULL,
	[Interno_FechaCorte] [datetime] NOT NULL,
	[Interno_ControlVersion] [nvarchar](25) NOT NULL,
	[Interno_FechaGeneracion] [datetime] NOT NULL CONSTRAINT [DF_{NombreTabla}_Data_Internos_FechaGeneracion]  DEFAULT (getdate()),
 CONSTRAINT [PK_{NombreTabla}] PRIMARY KEY CLUSTERED 
(
	[COD_CREDITO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

</query>