SELECT
'Cod_Cliente'					= CONCAT('"', TXT.Cod_Cliente,'"')  --
,'Nombre_Cliente'				= TXT.Nombre_Cliente
,'Num_Identificacion'			= CONCAT('"',  TXT.Num_Identificacion  ,'"') --
,'Tipo_persona'				= TXT.Tipo_persona
,'No_Creditos'				= No_Creditos
,'Deuda_total'				= Deuda_total
,'Cod_Credito'				= CONCAT('"', TXT.Cod_Credito ,'"') --
,'Tipo_Credito'				= TXT.Tipo_Credito
,'Tipo_Producto'				= TXT.Tipo_Producto
,'Sector'					= TXT.Sector
,'Fuente_Fin'					= TXT.Fuente_Fin
,'Codigo_MUC'					=  CONCAT('"',  TXT.Codigo_MUC   ,'"')--
,'Monto_Original'				= TXT.Monto_Original
,'Moneda'					= TXT.Moneda
,'Saldo_principal'			=  txt.Saldo_principal
,'Saldo_interes'				= txt.Saldo_interes
,'Monto_Ult_Pago_Ppal'		= txt.Monto_Ult_Pago_Ppal
,'Monto_Ult_Pago_Int'			= txt.Monto_Ult_Pago_Int
,'Fecha_Aprobacion'			= txt.Fecha_Aprobacion
,'Fecha_Desembolso'			= txt.Fecha_Desembolso
,'Fecha_Vencimiento'			= txt.Fecha_Vencimiento
,'Plazo'						= txt.Plazo
,'Fecha_primer_pago'			= txt.Fecha_primer_pago
,'Fecha_ultimo_pago_ppal'		= txt.Fecha_ultimo_pago_ppal
,'Fecha_ultimo_pago_int'		= txt.Fecha_ultimo_pago_int
,'Fecha_ingreso_mora_ppal'		= txt.Fecha_ingreso_mora_ppal
,'Fecha_ingreso_mora_int'		= txt.Fecha_ingreso_mora_int
,'Frecuencia_pago_ppal'		= TXT.Frecuencia_pago_ppal
,'Frecuencia_pago_int'		= TXT.Frecuencia_pago_int
,'Cuotas_programadas'			= txt.Cuotas_programadas
,'Cuotas_pagadas'				= txt.Cuotas_pagadas
,'Cuotas_vencidas'			= txt.Cuotas_vencidas
,'Modalidad'					= TXT.Modalidad
,'Dias_gracia'				= txt.Dias_gracia
,'Tipo_tasa'					= TXT.Tipo_tasa
,'Tasa_contractual'			= txt.Tasa_contractual
,'Tasa_vigente'				= txt.Tasa_vigente
,'Tasa_efectiva_vigente'		= txt.Tasa_efectiva_vigente
,'Tasa_mora'					= txt.Tasa_mora
,'Tipo_garantia'				= CASE WHEN LEN(TXT.Tipo_garantia) >0 THEN TXT.Tipo_garantia ELSE '' end 
,'Descripcion_garantia'		= CASE WHEN LEN(TXT.Descripcion_garantia)>0 THEN REPLACE(TXT.Descripcion_garantia,'|','') ELSE ''  END 
,'Valor_garantia'				= txt.Valor_garantia
,'Monto_cuota'				= txt.Monto_cuota
,'Cuota_total'				= txt.Cuota_total
,'Principal_corriente'		= txt.Principal_corriente
,'Principal_vencido'			= txt.Principal_vencido
,'Interes_Cte_Vgte'			= txt.Interes_Cte_Vgte
,'Interes_Cte_Vcdo'			= txt.Interes_Cte_Vcdo
,'Interes_moratorio'			= txt.Interes_moratorio
,'Fecha_prox_pago_ppal'		= txt.Fecha_prox_pago_ppal
,'Fecha_prox_pago_int'		= txt.Fecha_prox_pago_int
,'Dias_mora_principal'		= txt.Dias_mora_principal
,'Dias_mora_intereses'		= txt.Dias_mora_intereses
,'Clasificacion'				= txt.Clasificacion
,'Clasificacion_Cliente'		= txt.Clasificacion_Cliente
,'Provision'					= txt.Provision
,'Sucursal'					= TXT.Sucursal
,'ASESOR_CREDITO'				= TXT.ASESOR_CREDITO
FROM [Aux_cartera_SIBOIF_Resultado_20181031_1-0-0] TXT

